spring.application.name=cliniqueManager
server.port=${PORT:8080}

#Base de données
spring.datasource.url=jdbc:mysql://localhost:3306/clinique
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#IA Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.2

#Securité
jwt.secret=${JWT_SECRET:mysecretkey}
jwt.expiration=3600000
# Refresh token : 7 jours
jwt.refresh-expiration=604800000
app.admin.username=massamagoita
app.admin.password=massamag